using UnityEngine;
using IronFlag.Core;
using IronFlag.Menu;
using IronFlag.Vehicles;

namespace IronFlag.Audio
{
    /// <summary>
    /// A vehicle's engine: a loop that gets louder and higher the harder it is worked, and
    /// stops entirely when the vehicle is not out.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The only continuous sound in the game, and the only one that needs a component rather
    /// than a call. Everything else is a moment - a shot, a hit, a flag - and goes through
    /// <see cref="Sfx"/>. This one is a state, so it lives on the vehicle and is read every
    /// frame.
    /// </para>
    /// <para>
    /// <strong>What decides whether an engine runs at all is its bay.</strong>
    /// <see cref="VehicleBay.IsOnField"/> already means "out, with somebody at the controls",
    /// and every vehicle in this game either has a bay or is a rig somebody assembled by
    /// hand. So the twenty-odd vehicles parked in the two bunkers are silent for a reason
    /// this component did not have to invent, a deployed one idles, and a test rig with no
    /// bay runs - which is exactly what the bay's own <c>None</c> state already means.
    /// </para>
    /// <para>
    /// <strong>The helicopter needs no special case, only a different number.</strong> A
    /// rotor is at full song the moment it leaves the ground and barely changes with speed,
    /// where an engine follows the throttle - and that is the difference between an idle
    /// share of nine tenths and one of a quarter. Both go through the same arithmetic in
    /// <see cref="AudioMixdown.EngineLoudness"/>, and the prefab builder stamps the number
    /// on, the way it stamps every other per-vehicle figure.
    /// </para>
    /// <para>
    /// Flat, like everything else here: distance changes the volume and never the direction.
    /// See <see cref="AudioMixdown"/> for why a split screen cannot have it both ways.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Engine Audio")]
    public sealed class EngineAudio : MonoBehaviour
    {
        /// <summary>Name of the generated child the loop comes out of.</summary>
        public const string SourceNodeName = "Engine";

        [SerializeField]
        [Tooltip("The looping source. Generated by the vehicle prefab builder.")]
        private AudioSource loop;

        [SerializeField]
        [Tooltip("How loud this engine is with the throttle shut, in 0..1.")]
        [Range(0.0f, 1.0f)]
        private float idleShare = AudioMixdown.EngineIdleShare;

        private VehicleController vehicle;
        private VehicleBay bay;
        private bool looked;
        private SfxKind running = SfxKind.None;

        /// <summary>How loud this engine is with the throttle shut, in 0..1.</summary>
        public float IdleShare => idleShare;

        /// <summary>The looping source, or null on a rig that was built without one.</summary>
        /// <remarks>
        /// Exposed so a test can tell a vehicle built without a source from one whose source
        /// was dropped by a change to the builder - the same reason
        /// <c>VehicleWeapon.Flash</c> is exposed. Nothing in the game reads it.
        /// </remarks>
        public AudioSource Loop => loop;

        /// <summary>The clip this engine is looping, or <see cref="SfxKind.None"/> for silence.</summary>
        public SfxKind Running => running;

        /// <summary>
        /// Points this component at the source it plays through.
        /// </summary>
        /// <param name="source">The looping source.</param>
        /// <param name="idle">How loud the engine is with the throttle shut, in 0..1.</param>
        /// <remarks>Called by the vehicle prefab builder.</remarks>
        public void Configure(AudioSource source, float idle)
        {
            loop = source;
            idleShare = Mathf.Clamp01(idle);
        }

        /// <summary>
        /// Finds the vehicle this engine belongs to, once.
        /// </summary>
        /// <remarks>
        /// Lazy for the reason <see cref="IronFlag.Combat.VehicleWeapon"/> is: <c>Awake</c>
        /// does not run outside play mode, and the editor still asks a prefab on disk what it
        /// is wired to.
        /// </remarks>
        private void Look()
        {
            if (looked)
            {
                return;
            }

            looked = true;
            vehicle = GetComponent<VehicleController>();
            bay = GetComponent<VehicleBay>();
        }

        /// <summary>Whether this vehicle is out where it can be heard.</summary>
        private bool IsOut => bay == null || bay.IsOnField;

        private void Awake() => Look();

        private void OnDisable()
        {
            if (loop != null && loop.isPlaying)
            {
                loop.Stop();
            }

            running = SfxKind.None;
        }

        private void Update()
        {
            Look();

            if (loop == null || vehicle == null)
            {
                return;
            }

            // A paused match does not stop MonoBehaviours running, and audio is not
            // time-scaled, so without this the engines keep idling under the pause panel.
            bool audible = IsOut && Time.timeScale > 0.0f;
            if (!audible)
            {
                Quiet();
                return;
            }

            AudioDirector director = AudioDirector.Current;
            AudioCatalog catalog = director == null ? null : director.Catalog;
            SfxKind wanted = AudioRoster.EngineOf(vehicle.Kind);
            AudioClip clip = catalog == null ? null : catalog.ClipFor(wanted);

            if (clip == null)
            {
                Quiet();
                return;
            }

            if (running != wanted)
            {
                running = wanted;
                loop.clip = clip;
                loop.loop = true;
                loop.Play();
            }
            else if (!loop.isPlaying)
            {
                loop.Play();
            }

            float top = vehicle.Tuning == null ? 0.0f : vehicle.Tuning.MaxSpeed;
            float speed = vehicle.ForwardSpeed;
            float throttle = vehicle.CurrentInput.Throttle;

            loop.pitch = AudioMixdown.EnginePitch(speed, top);
            loop.volume = AudioMixdown.EngineLoudness(speed, top, throttle, idleShare)
                * AudioDirector.LoudnessAt(transform.position)
                * GameSettings.SoundVolume;
        }

        /// <summary>
        /// Stops the loop, if it is running.
        /// </summary>
        /// <remarks>
        /// Stopped rather than turned down to nothing. A vehicle sitting in its bunker for
        /// most of a match would otherwise be holding a voice open the whole time, and there
        /// are twenty-two of them.
        /// </remarks>
        private void Quiet()
        {
            if (loop.isPlaying)
            {
                loop.Stop();
            }

            running = SfxKind.None;
        }
    }
}
