using System.Globalization;
using System.Text;
using Curator.Core.Content;

namespace Curator.Core.Bots;

/// <summary>Writes out/balance-report.md: each bot's money, mana, outcomes and story trust (BUILD_BRIEF §8.4).</summary>
public static class BalanceReport
{
    /// <summary>Renders the report.</summary>
    /// <param name="results">One result per bot and seed.</param>
    /// <param name="guardrails">Broken guardrails, if any.</param>
    /// <returns>Markdown.</returns>
    public static string Render(IReadOnlyList<BotResult> results, IReadOnlyList<string> guardrails)
    {
        ArgumentNullException.ThrowIfNull(results);
        ArgumentNullException.ThrowIfNull(guardrails);
        var culture = CultureInfo.InvariantCulture;
        var md = new StringBuilder();
        md.AppendLine("# Balance report").AppendLine();
        md.AppendLine("Generated by the bot tests (BUILD_BRIEF §8.4). Each bot plays the week through commands only.").AppendLine();
        md.AppendLine(guardrails.Count == 0 ? "**Guardrails: all hold.**" : "**Guardrails broken:**").AppendLine();
        foreach (var line in guardrails)
        {
            md.AppendLine(culture, $"- {line}");
        }

        if (guardrails.Count > 0)
        {
            md.AppendLine();
        }

        md.AppendLine("| Bot | Seed | Money | Bonus mana | Mana granted | Loans | Declines | Walk-outs | Good | Unhelpful | Harm | Mixed |");
        md.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|---|");
        foreach (var r in results)
        {
            md.AppendLine(culture, $"| {r.Bot} | {r.Seed} | {r.Money} | {r.BonusMana} | {r.ManaGranted} | {r.Loans} | {r.Declines} | {r.WalkOuts} | {Count(r, OutcomeCategory.Good)} | {Count(r, OutcomeCategory.Unhelpful)} | {Count(r, OutcomeCategory.Harm)} | {Count(r, OutcomeCategory.Mixed)} |");
        }

        md.AppendLine().AppendLine("## Story patrons' final trust").AppendLine();
        var patrons = results.SelectMany(r => r.StoryTrust.Select(t => t.Name)).Distinct().ToList();
        md.AppendLine("| Bot | Seed | " + string.Join(" | ", patrons) + " |");
        md.AppendLine("|---|---|" + string.Concat(patrons.Select(_ => "---|")));
        foreach (var r in results)
        {
            var cells = patrons.Select(name => r.StoryTrust.FirstOrDefault(t => t.Name == name) is { } t
                ? (t.Met ? t.Trust.ToString(culture) : $"({t.Trust}, never came)")
                : "-");
            md.AppendLine(culture, $"| {r.Bot} | {r.Seed} | {string.Join(" | ", cells)} |");
        }

        return md.ToString();
    }

    private static int Count(BotResult result, OutcomeCategory category) => result.OutcomesByCategory.GetValueOrDefault(category);
}
