using System.Globalization;
using System.Text;
using Curator.Core.Content;

namespace Curator.Core.Bots;

/// <summary>Writes out/balance-report.md: each bot's money, mana, outcomes and story trust (BUILD_BRIEF §8.4).</summary>
public static class BalanceReport
{
    /// <summary>Renders the report.</summary>
    /// <param name="results">One result per bot and seed.</param>
    /// <param name="guardrails">The guardrails, checked across the seeds.</param>
    /// <returns>Markdown.</returns>
    public static string Render(IReadOnlyList<BotResult> results, IReadOnlyList<GuardrailResult> guardrails)
    {
        ArgumentNullException.ThrowIfNull(results);
        ArgumentNullException.ThrowIfNull(guardrails);
        var culture = CultureInfo.InvariantCulture;
        var md = new StringBuilder();
        md.AppendLine("# Balance report").AppendLine();
        md.AppendLine(culture, $"Generated by the bot tests (BUILD_BRIEF §8.4). Each bot plays the week through commands only, once per seed ({results.Select(r => r.Seed).Distinct().Count()} seeds).").AppendLine();
        if (guardrails.Count > 0)
        {
            md.AppendLine("## Guardrails").AppendLine();
            md.AppendLine("| Guardrail | Holds | Numbers |");
            md.AppendLine("|---|---|---|");
            foreach (var g in guardrails)
            {
                md.AppendLine(culture, $"| {g.Name} | {(g.Holds ? "yes" : "**no**")} | {g.Detail} |");
            }

            md.AppendLine();
        }

        md.AppendLine("## Silence").AppendLine();
        md.AppendLine("CONTENT_GUIDE §7 asks for about a third of the week's outcomes to be silent. Share of each bot's resolved outcomes (loans, declines and walk-outs) that never surface:").AppendLine();
        foreach (var bot in results.GroupBy(r => r.Bot))
        {
            var resolutions = bot.SelectMany(r => r.Session.State.Resolutions).ToList();
            var silent = resolutions.Count(r => r.OriginalChannel == OutcomeChannel.None);
            md.AppendLine(culture, $"- {bot.Key}: {(resolutions.Count == 0 ? 0 : 100.0 * silent / resolutions.Count):F0}% ({silent} of {resolutions.Count})");
        }

        md.AppendLine();
        md.AppendLine("## Each run").AppendLine();

        md.AppendLine("| Bot | Seed | Money | Bonus mana | Mana granted | Loans | Declines | Walk-outs | Good | Unhelpful | Harm | Mixed |");
        md.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|---|");
        foreach (var r in results)
        {
            md.AppendLine(culture, $"| {r.Bot} | {r.Seed} | {r.Money} | {r.BonusMana} | {r.ManaGranted} | {r.Loans} | {r.Declines} | {r.WalkOuts} | {Count(r, OutcomeCategory.Good)} | {Count(r, OutcomeCategory.Unhelpful)} | {Count(r, OutcomeCategory.Harm)} | {Count(r, OutcomeCategory.Mixed)} |");
        }

        md.AppendLine().AppendLine("## Story patrons' final trust").AppendLine();
        var patrons = results.SelectMany(r => r.StoryTrust.Select(t => t.Name)).Distinct().ToList();
        md.AppendLine("| Bot | Seed | " + string.Join(" | ", patrons) + " |");
        md.AppendLine("|---|---|" + string.Concat(patrons.Select(_ => "---|")));
        foreach (var r in results)
        {
            var cells = patrons.Select(name => r.StoryTrust.FirstOrDefault(t => t.Name == name) is { } t
                ? (t.Met ? t.Trust.ToString(culture) : $"({t.Trust}, never came)")
                : "-");
            md.AppendLine(culture, $"| {r.Bot} | {r.Seed} | {string.Join(" | ", cells)} |");
        }

        return md.ToString();
    }

    private static int Count(BotResult result, OutcomeCategory category) => result.OutcomesByCategory.GetValueOrDefault(category);
}
