<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <AdditionalFiles Include="*.yaml" />
    <AdditionalFiles Include="src/props/**" />
  </ItemGroup>
  
  <ItemGroup>
    <AdditionalFiles Remove="NuGet.config" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="docs\plan\chain-of-command-plan.md" />
    <None Include="docs\plan\race-condition-prevention.md" />
    <None Include="docs\plan\ship-event-command-plan.md" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="DotNetProjectFile.Analyzers.Sdk" PrivateAssets="all" />
  </ItemGroup>

</Project>
