<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AsyncFixer" Version="2.1.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="BenchmarkDotNet.Annotations" Version="0.15.8" />
    <PackageVersion Include="DotNetProjectFile.Analyzers" Version="1.9.0" />
    <PackageVersion Include="DotNetProjectFile.Analyzers.Sdk" Version="1.9.0" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageVersion Include="IDisposableAnalyzers" Version="4.0.8" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.201" />
    <PackageVersion Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.6.37110.2" />
    <PackageVersion Include="MSTest" Version="4.1.0" />
    <PackageVersion Include="Qowaiv.Analyzers.CSharp" Version="2.1.1" />
    <PackageVersion Include="SerilogAnalyzer" Version="0.15.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.21.0.135717" />
  </ItemGroup>
</Project>
