using UnityEngine;
using IronFlag.Combat;

namespace IronFlag.Vfx
{
    /// <summary>
    /// The smoke something gives off once it has been hurt, and the column it throws up when
    /// it finally goes.
    /// </summary>
    /// <remarks>
    /// <para>
    /// One component for both, because they are one story told at two volumes: a hull or a
    /// building starts smoking when it is half gone, keeps smoking while it is still
    /// standing, and stops when there is nothing left to smoke. The moment it stops is the
    /// moment the column goes up, so the two effects can never overlap or leave a gap - and
    /// neither can be forgotten separately, because forgetting one means the other has
    /// nothing to hand over to.
    /// </para>
    /// <para>
    /// It works on an <see cref="IDamageable"/> rather than on a vehicle or a structure, so
    /// a tank at forty per cent and a wall at forty per cent smoke for the same reason and
    /// through the same code. That is why <see cref="IDamageable.Fraction"/> exists.
    /// </para>
    /// <para>
    /// <strong>It polls rather than subscribing</strong>, which is a deliberate choice
    /// against this project's usual grain. <see cref="VehicleHealth"/> raises an event when a
    /// vehicle dies and when it is repaired, and nothing at all when it is merely hit -
    /// adding a third event so that smoke could hear about it would put a cosmetic concern
    /// into the damage model, which that class's own remarks argue against. A float compare
    /// per object per frame, on a map with perhaps forty destructibles, is not a cost worth
    /// designing around.
    /// </para>
    /// <para>
    /// The column is spawned <em>detached</em>. A wrecked vehicle is taken off the field and
    /// sent back to its bunker within the second, and smoke parented to it would leave with
    /// it - so the one effect whose whole job is to mark where something died has to stop
    /// belonging to the thing that died.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Damage Smoke")]
    public sealed class DamageSmoke : MonoBehaviour
    {
        /// <summary>How much of the pool has to be gone before it smokes.</summary>
        /// <remarks>
        /// Half, which is <see cref="IronFlag.Destruction.StructureTuning.DamagedAt"/>'s
        /// default and deliberately the same number: a building swaps to its cracked model at
        /// exactly the point it starts smoking, so the two read as one event rather than as
        /// two things that happen near each other. A vehicle has no model to swap, so for a
        /// vehicle this is the only sign it is hurt short of a health bar.
        /// </remarks>
        public const float SmokesBelow = 0.5f;

        [SerializeField]
        [Tooltip("Plume that runs while it is hurt. Generated by the prefab builder.")]
        private ParticleSystem plume;

        [SerializeField]
        [Tooltip("Column thrown up where it dies. Generated by the prefab builder.")]
        private ParticleBurst column;

        [SerializeField]
        [Tooltip("Metres across the death column should be.")]
        private float columnSize = 3.0f;

        private IDamageable hull;
        private bool looked;
        private bool smoking;
        private bool collapsed;

        /// <summary>Whether the plume is running right now.</summary>
        public bool IsSmoking => smoking;

        /// <summary>Metres across the death column is.</summary>
        public float ColumnSize => columnSize;

        /// <summary>The plume that runs while it is hurt, or null on a rig that has none.</summary>
        public ParticleSystem Plume => plume;

        /// <summary>The column thrown up where it dies, or null on a rig that has none.</summary>
        public ParticleBurst Column => column;

        /// <summary>
        /// Points this component at the parts the prefab builder generated for it.
        /// </summary>
        /// <param name="hurtPlume">Particle system that runs while it is damaged.</param>
        /// <param name="deathColumn">Burst prefab thrown up where it dies, or null.</param>
        /// <param name="size">Metres across that column should be.</param>
        /// <remarks>Called by the prefab builder.</remarks>
        public void Configure(ParticleSystem hurtPlume, ParticleBurst deathColumn, float size)
        {
            plume = hurtPlume;
            column = deathColumn;
            columnSize = Mathf.Max(0.1f, size);
        }

        /// <summary>
        /// Returns whether something in this condition should be giving off smoke.
        /// </summary>
        /// <param name="fraction">Hit points remaining as a fraction of full, in 0..1.</param>
        /// <param name="destroyed">Whether it has already been finished off.</param>
        /// <returns><c>true</c> when the plume should be running.</returns>
        /// <remarks>
        /// Static and side-effect free, like every other animation rule in this project, so
        /// the one decision this component makes can be checked without hurting anything.
        /// A wreck is excluded rather than falling out of the fraction: a destroyed thing is
        /// at zero, which is below the threshold, and would otherwise smoke for ever.
        /// </remarks>
        public static bool ShouldSmoke(float fraction, bool destroyed)
            => !destroyed && fraction <= SmokesBelow;

        /// <summary>Where the smoke comes from, in world space.</summary>
        private Vector3 Origin => plume == null ? transform.position : plume.transform.position;

        private void Awake() => Look();

        private void OnDisable()
        {
            // A vehicle sent home for repairs is switched off rather than destroyed, and a
            // plume left running on it comes back with it still smoking at full health. The
            // collapsed latch is deliberately *not* cleared here: a wreck that is switched
            // off and on again is still a wreck, and clearing it would put up a second column
            // the frame it came back. It clears when the hull is alive again, which is the
            // thing it actually means.
            Show(false);
        }

        private void Update()
        {
            Look();
            if (hull == null)
            {
                return;
            }

            if (hull.IsDestroyed)
            {
                if (!collapsed)
                {
                    collapsed = true;
                    Show(false);
                    ParticleBurst.Spawn(column, Origin, columnSize);
                }

                return;
            }

            // Back from the dead: a structure put back up by the level editor, or a vehicle
            // that redeployed. Either way the next death owes another column.
            collapsed = false;
            Show(ShouldSmoke(hull.Fraction, false));
        }

        /// <summary>
        /// Starts or stops the plume, doing nothing when it is already in that state.
        /// </summary>
        /// <param name="on">Whether it should be emitting.</param>
        /// <remarks>
        /// Stopped rather than cleared, so the puffs already in the air drift up and fade out
        /// on their own. A repaired vehicle whose smoke vanished between two frames would
        /// read as a rendering glitch rather than as a repair.
        /// </remarks>
        private void Show(bool on)
        {
            if (on == smoking || plume == null)
            {
                return;
            }

            smoking = on;
            if (on)
            {
                plume.Play(false);
            }
            else
            {
                plume.Stop(false, ParticleSystemStopBehavior.StopEmitting);
            }
        }

        /// <summary>
        /// Finds what this is bolted to, once.
        /// </summary>
        /// <remarks>
        /// Lazy for the reason <c>VehicleWeapon.Look</c> is: <c>Awake</c> does not run
        /// outside play mode, and the editor asks a prefab on disk what it is wired to.
        /// </remarks>
        private void Look()
        {
            if (looked)
            {
                return;
            }

            looked = true;
            hull = GetComponent<IDamageable>();
        }
    }
}
