using UnityEngine;
using IronFlag.Levels;
using IronFlag.Vehicles;

namespace IronFlag.Vfx
{
    /// <summary>
    /// What a ground vehicle kicks up behind it: more of it the faster it goes, more of it
    /// on soft ground than on a road, and the colour of whatever it is driving over.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is what <see cref="GroundVehicle.Standing"/> and
    /// <see cref="GroundVehicle.Underfoot"/> were for. Both have existed since the surfaces
    /// pass and neither had a second reader: the movement model uses the grip and the fuel
    /// pool uses the draw, and nothing at all used the fact that a vehicle knows what it is
    /// driving on. A dust trail is the obvious thing to do with it, and doing it this way -
    /// sampling the surface table rather than authoring a dust colour - means the map cannot
    /// grow a surface whose dust is the wrong colour, in exactly the way a coastline cannot
    /// grow a bank colour that is not its own surface taken down a step.
    /// </para>
    /// <para>
    /// <strong>Both numbers are derived from the surface table rather than added to it.</strong>
    /// The colour is the ground's own, lifted towards white because airborne dust catches
    /// the light from every side; the amount is read off <see cref="SurfaceTuning.Grip"/>,
    /// because soft ground is exactly the ground that both slows a vehicle and comes up
    /// behind it. So a beach throws a cloud, open country puffs, a road barely marks, and
    /// nobody had to write three numbers down - see <see cref="Dustiness"/>.
    /// </para>
    /// <para>
    /// The helicopter has none of this and needs no check to be excluded, for the same
    /// reason it never asks what it is flying over: this component goes on a
    /// <see cref="GroundVehicle"/>, and a helicopter is not one.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Dust Trail")]
    public sealed class DustTrail : MonoBehaviour
    {
        /// <summary>Metres per second below which nothing is kicked up at all.</summary>
        /// <remarks>
        /// A vehicle creeping into position should not be trailing a cloud. It is low enough
        /// that anything a player would call "driving" is over it, and high enough that the
        /// jostle of a vehicle settling against a wall is not.
        /// </remarks>
        public const float MovingAbove = 1.5f;

        /// <summary>How pale dust is against the ground it came off, in 0..1.</summary>
        /// <remarks>
        /// Just under half. Airborne dust is the same material lit from every side at once
        /// instead of only from above, so it reads lighter than the ground - and it has to,
        /// or a dust trail over open country is a green smear nobody can see.
        /// </remarks>
        public const float Paleness = 0.45f;

        [SerializeField]
        [Tooltip("The trail itself. Generated by the prefab builder.")]
        private ParticleSystem dust;

        [SerializeField]
        [Tooltip("Particles a second at full speed on the softest ground.")]
        private float peakRate = 30.0f;

        private GroundVehicle vehicle;
        private bool looked;
        private SurfaceKind painted = SurfaceKind.None;

        /// <summary>Particles a second at full speed on the softest ground.</summary>
        public float PeakRate => peakRate;

        /// <summary>The trail itself, or null on a rig that has none.</summary>
        public ParticleSystem Dust => dust;

        /// <summary>
        /// Points this component at the trail the prefab builder generated for it.
        /// </summary>
        /// <param name="trail">Particle system that draws the dust.</param>
        /// <param name="rate">Particles a second at full speed on the softest ground.</param>
        /// <remarks>Called by the prefab builder.</remarks>
        public void Configure(ParticleSystem trail, float rate)
        {
            dust = trail;
            peakRate = Mathf.Max(0.0f, rate);
        }

        /// <summary>
        /// Returns how readily a surface gives its dust up, as a multiple of the peak rate.
        /// </summary>
        /// <param name="surface">The ground being driven on.</param>
        /// <returns>A multiplier in 0..1; zero for anything that is not ground.</returns>
        /// <remarks>
        /// <para>
        /// Derived from <see cref="SurfaceTuning.Grip"/> and deliberately not a column of its
        /// own. Soft ground is loose ground: the same property that takes a fifth off the
        /// jeep's top speed on a beach is the property that puts a beach in the air behind
        /// it, so a surface that costs speed pays in dust and a surface that gives speed
        /// stays clean. It falls out at about a full cloud on sand, two fifths over open
        /// country and a quarter on asphalt - a spread you can read at a glance, off numbers
        /// that were balanced for something else entirely.
        /// </para>
        /// <para>
        /// Water gives up nothing, which is <see cref="SurfaceTuning.Drowns"/> rather than a
        /// list of the wet surfaces - the same question asked once. A vehicle over water is
        /// a vehicle about to drown, and a plume of spray behind it as it sinks would be
        /// cheerful about it.
        /// </para>
        /// </remarks>
        public static float Dustiness(SurfaceTuning surface)
        {
            if (surface == null || surface.Drowns)
            {
                return 0.0f;
            }

            return Mathf.Clamp01((1.15f - surface.Grip) / 0.35f);
        }

        /// <summary>
        /// Returns what colour the dust off a surface is.
        /// </summary>
        /// <param name="surface">The ground being driven on.</param>
        /// <returns>The surface's own colour, lifted towards white.</returns>
        public static Color TintFor(SurfaceTuning surface)
            => surface == null
                ? Color.grey
                : Color.Lerp(surface.Colour, Color.white, Paleness);

        /// <summary>
        /// Returns how hard the trail should be emitting.
        /// </summary>
        /// <param name="speed">How fast the vehicle is going, in metres per second.</param>
        /// <param name="topSpeed">The vehicle's own top speed, in metres per second.</param>
        /// <param name="surface">The ground it is on.</param>
        /// <param name="peak">Particles a second at full speed on the softest ground.</param>
        /// <returns>Particles a second, which is zero for anything standing still.</returns>
        /// <remarks>
        /// Speed is taken as a magnitude, so reversing raises dust exactly as driving forward
        /// does. It ramps from <see cref="MovingAbove"/> rather than from nothing, which is
        /// what puts a clean gap between a vehicle parked and a vehicle pulling away.
        /// </remarks>
        public static float RateFor(float speed, float topSpeed, SurfaceTuning surface, float peak)
        {
            if (topSpeed <= MovingAbove || peak <= 0.0f)
            {
                return 0.0f;
            }

            float share = Mathf.InverseLerp(MovingAbove, topSpeed, Mathf.Abs(speed));
            return share * peak * Dustiness(surface);
        }

        /// <summary>
        /// Draws the trail as it would look after driving for a while on one surface.
        /// </summary>
        /// <param name="surface">Ground to pretend it is on.</param>
        /// <param name="speed">Speed to pretend it is doing, in metres per second.</param>
        /// <param name="seconds">How long it has been driving.</param>
        /// <remarks>
        /// For the preview scene, for the reason <c>MuzzleFlash.PoseAt</c> exists - particles
        /// do not simulate outside play mode. It takes the surface as an argument rather than
        /// reading it off the vehicle, because the whole point of photographing a dust trail
        /// is to see the four surfaces beside each other, and a preview scene has no map for
        /// a vehicle to be standing on.
        /// </remarks>
        public void PoseAt(SurfaceTuning surface, float speed, float seconds)
        {
            Look();
            if (dust == null)
            {
                return;
            }

            float topSpeed = vehicle == null ? 10.0f : vehicle.Tuning.MaxSpeed;

            Retint(surface);

            ParticleSystem.EmissionModule emission = dust.emission;
            emission.rateOverTime = RateFor(speed, topSpeed, surface, peakRate);

            dust.Simulate(Mathf.Max(0.0f, seconds), false, true);
        }

        private void Awake() => Look();

        private void Update()
        {
            Look();
            if (dust == null || vehicle == null)
            {
                return;
            }

            Repaint();

            ParticleSystem.EmissionModule emission = dust.emission;
            emission.rateOverTime = RateFor(
                vehicle.ForwardSpeed, vehicle.Tuning.MaxSpeed, vehicle.Underfoot, peakRate);
        }

        /// <summary>
        /// Recolours the trail when the ground under the vehicle changes.
        /// </summary>
        /// <remarks>
        /// Only on a change, for the reason <c>GroundVehicle.ReadTheGround</c> only looks up
        /// its row on one: a vehicle crosses a handful of boundaries a minute, and writing a
        /// colour into a module fifty times a second to say the same thing is fifty times the
        /// work for none of the effect. Puffs already in the air keep the colour of the ground
        /// they came off, which is correct rather than a compromise - dust does not change
        /// colour once it is airborne.
        /// </remarks>
        private void Repaint()
        {
            if (vehicle.Standing == painted)
            {
                return;
            }

            painted = vehicle.Standing;

            Retint(vehicle.Underfoot);
        }

        /// <summary>
        /// Sets the trail's start colour from a surface, keeping whatever alpha it already had.
        /// </summary>
        /// <remarks>
        /// The one place <see cref="dust"/>'s main module is written to repaint it, so
        /// <see cref="PoseAt"/> and <see cref="Repaint"/> stay the same colour by construction
        /// rather than by keeping two copies of the same three lines in step by hand.
        /// </remarks>
        private void Retint(SurfaceTuning surface)
        {
            ParticleSystem.MainModule main = dust.main;
            Color tint = TintFor(surface);
            main.startColor = new Color(tint.r, tint.g, tint.b, main.startColor.color.a);
        }

        private void Look()
        {
            if (looked)
            {
                return;
            }

            looked = true;
            vehicle = GetComponent<GroundVehicle>();
        }
    }
}
