using UnityEngine;
using IronFlag.Levels;

namespace IronFlag.Vfx
{
    /// <summary>
    /// A stain left on the ground: the scorch under a blast, and the burn a flattened
    /// building leaves behind it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The counterpart of <see cref="IronFlag.Combat.Explosion"/> and
    /// <see cref="ParticleBurst"/>, and deliberately the same shape of thing - spawn it where
    /// something happened, tell it how big, forget about it. What differs is how long it is
    /// forgotten for: a blast fades its mark out and takes it away, and a collapse does not,
    /// because the rubble it belongs to is still standing there.
    /// </para>
    /// <para>
    /// <strong>A quad, not a decal projector.</strong> URP has one, this project's renderer
    /// assets do not carry its renderer feature, and a projector exists to lay a mark across
    /// geometry whose shape is unknown. The shape here is known exactly: every square metre
    /// of ground is at <c>y = 0</c> and flat, because
    /// <see cref="IronFlag.Combat.CombatPlane"/> resolves every round on that plane. A quad
    /// a centimetre above it is the same picture with no renderer feature, no depth
    /// sampling, and no texture - see <c>RF_Mark.shader</c>, which multiplies rather than
    /// blends so that one mark is the right colour on grass, on sand and on a road without
    /// knowing that any of them exist.
    /// </para>
    /// <para>
    /// Nothing spawns one directly. Every blast in the game goes through
    /// <see cref="IronFlag.Combat.Explosion.Spawn"/>, so hanging the scorch off that is one
    /// hook rather than a call at every weapon, wreck and collapse - and it makes the mark
    /// the size of the blast that made it for free, which is the relationship anybody would
    /// have written by hand.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Ground Mark")]
    public sealed class GroundMark : MonoBehaviour
    {
        /// <summary>How far above the ground a mark is drawn, in metres.</summary>
        /// <remarks>
        /// A centimetre and a bit: far enough that no view in the game can catch it
        /// z-fighting with the sheet under it, and near enough that a vehicle's shadow still
        /// falls across it as though it were the ground. The sheets themselves are only two
        /// centimetres apart - see <c>LevelBuilder.CoastLift</c> - so this cannot grow much.
        /// </remarks>
        public const float Height = 0.012f;

        /// <summary>Blasts smaller than this leave nothing, in metres.</summary>
        /// <remarks>
        /// The chaingun and the autocannon fire several rounds a second each and their
        /// impacts come out around half a metre, so without a floor here a firefight would
        /// carpet the ground in scorch marks inside ten seconds. Above it are the grenade,
        /// the cannon, the rocket and every wreck - the shots that are events.
        /// </remarks>
        public const float SmallestBlast = 1.2f;

        /// <summary>How much of a blast's radius its scorch covers.</summary>
        /// <remarks>
        /// Rather more than half. A fireball is a sphere and its mark is the part of the
        /// ground that was inside it, which is smaller than the sphere and not by a little.
        /// </remarks>
        public const float BlastShare = 0.55f;

        /// <summary>How long a blast's scorch lasts, in seconds.</summary>
        /// <remarks>
        /// Long enough to still be there when the fight moves back over the same ground, and
        /// short enough that a long match does not end up reading its own history. A
        /// collapse's mark is spawned with zero instead and stays, because what left it is
        /// still standing there as rubble.
        /// </remarks>
        public const float Fade = 22.0f;

        /// <summary>The last share of its life a mark spends fading out.</summary>
        private const float Fading = 0.5f;

        [SerializeField]
        [Tooltip("The quad the mark is drawn on. Generated by the VFX prefab builder.")]
        private Renderer face;

        [SerializeField]
        [Tooltip("Metres across the prefab's own quad is.")]
        private float authoredSize = 1.0f;

        private static readonly int Tint = Shader.PropertyToID("_BaseColor");

        private MaterialPropertyBlock paint;
        private Color stain = Color.white;
        private bool read;
        private float life;
        private float left;

        /// <summary>Metres across the prefab's own quad is.</summary>
        public float AuthoredSize => authoredSize;

        /// <summary>Seconds this mark lasts, or zero when it stays.</summary>
        public float Life => life;

        /// <summary>
        /// Leaves a mark on the ground, if there is any ground there to mark.
        /// </summary>
        /// <param name="prefab">The mark to make, or <c>null</c> for a rig that has none.</param>
        /// <param name="at">Where it happened, in world space; only x and z are used.</param>
        /// <param name="across">How many metres across the mark should be.</param>
        /// <param name="seconds">How long it lasts, or zero to leave it there.</param>
        /// <returns>The mark, or <c>null</c> when none was left.</returns>
        /// <remarks>
        /// <para>
        /// Refused over water, which is <see cref="SurfaceTuning.Drowns"/> asked of the
        /// loaded map rather than a height test against the waterline: a shell that goes off
        /// a metre above the sea is over water and one that goes off a metre above the beach
        /// is not, and their heights are the same. A scene with no map loaded is allowed to
        /// mark, because that is a preview scene and refusing there would make the mark
        /// impossible to photograph.
        /// </para>
        /// <para>
        /// Refused outside play mode too, and that is a lesson rather than tidiness: nothing
        /// steps a spawned effect in the editor, so anything spawned there parks itself in
        /// the scene and reads as geometry. The doors pass lost an afternoon to a
        /// <c>DebrisBurst</c> frozen at the origin of every structure a preview knocked down
        /// and mistook it for the rubble being a metre tall. A preview that wants a mark can
        /// still build one by hand with <see cref="Configure"/>, exactly as one that wants a
        /// dust trail poses it rather than driving.
        /// </para>
        /// </remarks>
        public static GroundMark Spawn(GroundMark prefab, Vector3 at, float across, float seconds)
        {
            if (prefab == null || !Application.isPlaying
                || across < SmallestBlast || !OverLand(at))
            {
                return null;
            }

            GroundMark made = Instantiate(
                prefab, new Vector3(at.x, Height, at.z), Turned(at));
            made.Configure(across, seconds);
            return made;
        }

        /// <summary>
        /// Points this component at the quad it draws on.
        /// </summary>
        /// <param name="quad">The renderer to stain.</param>
        /// <param name="size">Metres across that quad is.</param>
        /// <remarks>Called by the prefab builder.</remarks>
        public void Wire(Renderer quad, float size)
        {
            face = quad;
            authoredSize = size;
        }

        /// <summary>
        /// Sizes a mark and starts its clock.
        /// </summary>
        /// <param name="across">How many metres across it should be.</param>
        /// <param name="seconds">How long it lasts, or zero to leave it there.</param>
        public void Configure(float across, float seconds)
        {
            float size = authoredSize <= 0.0f ? 1.0f : authoredSize;
            transform.localScale = Vector3.one * (across / size);

            life = Mathf.Max(0.0f, seconds);
            left = life;
            Paint(1.0f);
        }

        /// <summary>
        /// Reports whether a point is over something a mark could be left on.
        /// </summary>
        /// <param name="at">Point to test; only x and z are used.</param>
        /// <returns><c>true</c> when the map says that is ground, or when there is no map.</returns>
        private static bool OverLand(Vector3 at)
        {
            LevelDefinition level = LevelLoader.Current;
            if (level == null || level.Field == null)
            {
                return true;
            }

            return !SurfaceTuning.For(level.Field.At(at)).Drowns;
        }

        /// <summary>
        /// Picks which way round a mark lies.
        /// </summary>
        /// <param name="at">Where the mark is, in world space.</param>
        /// <returns>Flat on the ground, spun by an amount that depends on where it is.</returns>
        /// <remarks>
        /// Off the position rather than off <see cref="Random"/>, so that two marks in the
        /// same place are the same mark and a still of a match is the same still twice. The
        /// two multipliers are coprime-ish and unrelated to the one-metre cell the map is
        /// measured in, so neighbouring marks do not come out aligned.
        /// </remarks>
        private static Quaternion Turned(Vector3 at)
            => Quaternion.Euler(
                0.0f, Mathf.Repeat((at.x * 47.3f) + (at.z * 91.7f), 360.0f), 0.0f);

        /// <summary>
        /// Fades a mark out and takes it away when it has gone.
        /// </summary>
        /// <remarks>
        /// A mark with no life left in it was spawned to stay, so it is never touched again -
        /// which is also what keeps the cost of the permanent ones at nothing: the map has as
        /// many structures as it has, and each of them can only collapse once.
        /// </remarks>
        private void Update()
        {
            if (life <= 0.0f || !Application.isPlaying)
            {
                return;
            }

            left -= Time.deltaTime;
            if (left <= 0.0f)
            {
                Destroy(gameObject);
                return;
            }

            Paint(Mathf.Clamp01(left / (life * Fading)));
        }

        /// <summary>
        /// Sets how much of the mark is still there.
        /// </summary>
        /// <param name="share">One for a fresh mark, zero for one that has gone.</param>
        /// <remarks>
        /// Towards white rather than towards transparent, because the shader multiplies:
        /// white is the colour that leaves the ground exactly as it found it, so fading a
        /// stain out and switching it off are the same operation.
        /// </remarks>
        private void Paint(float share)
        {
            if (face == null)
            {
                return;
            }

            paint ??= new MaterialPropertyBlock();
            face.GetPropertyBlock(paint);
            paint.SetColor(Tint, Color.Lerp(Color.white, Stain(), Mathf.Clamp01(share)));
            face.SetPropertyBlock(paint);
        }

        /// <summary>
        /// Returns what this mark's material stains the ground with.
        /// </summary>
        /// <returns>The material's own colour, or white when there is nothing to read.</returns>
        /// <remarks>
        /// Read on first use rather than in <c>Awake</c>, and that is not a style preference:
        /// <c>Awake</c> does not run in the editor, so a mark posed by a preview scene got
        /// white - which under a multiply is the colour that leaves the ground exactly as it
        /// found it. The first marks row came out completely blank and looked for all the
        /// world like a shader that was not drawing.
        /// </remarks>
        private Color Stain()
        {
            if (read)
            {
                return stain;
            }

            read = true;
            if (face != null && face.sharedMaterial != null && face.sharedMaterial.HasProperty(Tint))
            {
                stain = face.sharedMaterial.GetColor(Tint);
            }

            return stain;
        }
    }
}
