using UnityEngine;
using IronFlag.Levels;
using IronFlag.Vehicles;

namespace IronFlag.Vfx
{
    /// <summary>
    /// The two lines a ground vehicle leaves behind it: deep on a beach, faint on open
    /// country, barely there on a road, and nothing at all on water.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The other half of <see cref="DustTrail"/>, and it shares that component's one
    /// derivation rather than adding a second: how readily a surface gives its dust up is
    /// how readily it takes a wheel mark, because both are the same fact about loose ground -
    /// see <see cref="DustTrail.Dustiness"/>. So a beach is scored, a road is not, and
    /// nobody had to write a third column in the surfaces table.
    /// </para>
    /// <para>
    /// <strong>The colour is not read off the ground, and that is the point of the
    /// shader.</strong> Dust has to be tinted per surface because it is a thing in the air
    /// in front of the ground; a wheel mark is the ground, pressed down, and
    /// <c>RF_Mark.shader</c> multiplies rather than blends - so one white-to-dark ribbon
    /// comes out the right colour on grass, on sand and on asphalt at once, including across
    /// the seam between two of them. What the surface decides here is how <em>dark</em> the
    /// ribbon is, which is one number rather than a colour.
    /// </para>
    /// <para>
    /// A <see cref="TrailRenderer"/> rather than marks stamped down at intervals: it is one
    /// component per wheel, it ages its own tail through a colour gradient without anything
    /// having to count, and it allocates nothing per metre driven. What it costs is the two
    /// traps below - it emits in world space, which is exactly right until the vehicle stops
    /// travelling through the world to get somewhere.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Tyre Tracks")]
    public sealed class TyreTracks : MonoBehaviour
    {
        /// <summary>How far above the ground a track is drawn, in metres.</summary>
        /// <remarks>
        /// A hair under <see cref="GroundMark.Height"/>, so that a scorch mark laid over a
        /// wheel track draws on top of it rather than fighting it for the same depth. Which
        /// of the two wins is arbitrary; that one of them wins every time is not.
        /// </remarks>
        public const float Height = 0.010f;

        /// <summary>How dark a track gets on the softest ground, in 0..1.</summary>
        /// <remarks>
        /// Half. The shader multiplies, so this is the share of the ground's own brightness
        /// the deepest part of a rut takes away - and a rut that took all of it would be a
        /// black line drawn across a game whose whole readability argument is value contrast.
        /// </remarks>
        public const float Darkest = 0.5f;

        /// <summary>
        /// Metres a vehicle can move in one frame before its tracks are cut.
        /// </summary>
        /// <remarks>
        /// The trap that comes with a trail renderer: its points are in world space, so a
        /// vehicle that is <em>put</em> somewhere rather than driven there - sent home to its
        /// bunker after being shot, or deployed out of one - drags a ribbon straight across
        /// the map behind it. Nothing in the game moves this far in a frame under its own
        /// power; the fastest thing on the map does about a fifth of it at sixty frames a
        /// second.
        /// </remarks>
        public const float Teleport = 4.0f;

        [SerializeField]
        [Tooltip("The left-hand track. Generated by the vehicle prefab builder.")]
        private TrailRenderer left;

        [SerializeField]
        [Tooltip("The right-hand track. Generated by the vehicle prefab builder.")]
        private TrailRenderer right;

        [SerializeField]
        [Tooltip("Where the left wheels meet the ground, in the vehicle's own space.")]
        private Vector3 leftAt = new Vector3(-0.8f, 0.0f, 0.0f);

        [SerializeField]
        [Tooltip("Where the right wheels meet the ground, in the vehicle's own space.")]
        private Vector3 rightAt = new Vector3(0.8f, 0.0f, 0.0f);

        /// <summary>
        /// Flat on the ground, which is where a trail renderer's local z axis has to point
        /// for its ribbon to lie in the ground rather than stand up out of it.
        /// </summary>
        private static readonly Quaternion Lying = Quaternion.Euler(-90.0f, 0.0f, 0.0f);

        private GroundVehicle vehicle;
        private bool looked;
        private Vector3 wasAt;
        private bool travelled;

        /// <summary>The left-hand track, or null on a rig that has none.</summary>
        public TrailRenderer Left => left;

        /// <summary>The right-hand track, or null on a rig that has none.</summary>
        public TrailRenderer Right => right;

        /// <summary>
        /// Wires the tracks up.
        /// </summary>
        /// <param name="leftTrack">The left-hand track.</param>
        /// <param name="rightTrack">The right-hand track.</param>
        /// <param name="halfWidth">Metres from the middle of the vehicle to its wheels.</param>
        public void Configure(TrailRenderer leftTrack, TrailRenderer rightTrack, float halfWidth)
        {
            left = leftTrack;
            right = rightTrack;
            leftAt = new Vector3(-halfWidth, 0.0f, 0.0f);
            rightAt = new Vector3(halfWidth, 0.0f, 0.0f);
        }

        /// <summary>
        /// Returns how dark a track on one surface is.
        /// </summary>
        /// <param name="surface">The ground being driven on.</param>
        /// <returns>An alpha in 0..1; zero for anything that is not ground.</returns>
        /// <remarks>
        /// <see cref="DustTrail.Dustiness"/> scaled, so the two effects cannot disagree about
        /// which ground is soft. A surface that throws a cloud is a surface that takes a rut,
        /// and both of them fall out of <see cref="SurfaceTuning.Grip"/> - the number that was
        /// balanced for how a jeep handles on a beach.
        /// </remarks>
        public static float Darkness(SurfaceTuning surface) => DustTrail.Dustiness(surface) * Darkest;

        /// <summary>
        /// Lays both tracks on the ground behind the vehicle.
        /// </summary>
        /// <remarks>
        /// In <see cref="LateUpdate"/> rather than <see cref="Update"/>, because a trail
        /// renderer records where its transform is at the end of the frame and the vehicle
        /// has not finished moving until then. A track laid a frame behind the wheel that cut
        /// it is a track that swings wide of every corner.
        /// </remarks>
        private void LateUpdate()
        {
            if (!Application.isPlaying)
            {
                return;
            }

            Look();

            SurfaceTuning underfoot = vehicle == null ? null : vehicle.Underfoot;
            float dark = Darkness(underfoot);
            float speed = vehicle == null ? 0.0f : Mathf.Abs(vehicle.ForwardSpeed);

            // The same threshold the dust uses, so a vehicle inching into position neither
            // throws a cloud nor cuts a rut, and the two start together when it pulls away.
            bool cutting = dark > 0.0f && speed > DustTrail.MovingAbove;

            Vector3 now = transform.position;
            bool jumped = travelled && (now - wasAt).sqrMagnitude > Teleport * Teleport;
            wasAt = now;
            travelled = true;

            Lay(left, leftAt, dark, cutting, jumped);
            Lay(right, rightAt, dark, cutting, jumped);
        }

        /// <summary>
        /// Cuts both tracks, so a vehicle taking the field starts on clean ground.
        /// </summary>
        private void OnEnable()
        {
            travelled = false;
            Cut(left);
            Cut(right);
        }

        /// <summary>
        /// Puts one track where its wheels are and tells it whether to be marking.
        /// </summary>
        /// <param name="trail">The track.</param>
        /// <param name="at">Where those wheels are, in the vehicle's own space.</param>
        /// <param name="dark">How dark a mark this ground takes.</param>
        /// <param name="cutting">Whether the vehicle is moving over ground that marks.</param>
        /// <param name="jumped">Whether the vehicle was moved rather than driven.</param>
        private void Lay(TrailRenderer trail, Vector3 at, float dark, bool cutting, bool jumped)
        {
            if (trail == null)
            {
                return;
            }

            if (jumped)
            {
                Cut(trail);
            }

            Vector3 world = transform.TransformPoint(at);
            trail.transform.SetPositionAndRotation(
                new Vector3(world.x, Height, world.z), Lying);

            trail.emitting = cutting;
            trail.startColor = new Color(1.0f, 1.0f, 1.0f, dark);
            trail.endColor = new Color(1.0f, 1.0f, 1.0f, 0.0f);
        }

        /// <summary>
        /// Throws away everything a track has laid so far.
        /// </summary>
        /// <param name="trail">The track, or <c>null</c>.</param>
        private static void Cut(TrailRenderer trail)
        {
            if (trail != null)
            {
                trail.Clear();
            }
        }

        /// <summary>
        /// Finds the vehicle these tracks belong to, once.
        /// </summary>
        /// <remarks>
        /// The same shape as <see cref="DustTrail"/>'s: looked for rather than serialised,
        /// and remembered as "looked" rather than as "found", so a rig without one asks the
        /// question once instead of every frame.
        /// </remarks>
        private void Look()
        {
            if (looked)
            {
                return;
            }

            looked = true;
            vehicle = GetComponent<GroundVehicle>();
        }
    }
}
