namespace AdventureEngine.Domain;

/// <summary>
/// The complete world definition generated by the Director agent at game start.
/// </summary>
public sealed class WorldManifest
{
    [JsonPropertyName("title")]
    public string Title { get; init; } = string.Empty;

    [JsonPropertyName("premise")]
    public string Premise { get; init; } = string.Empty;

    [JsonPropertyName("lore")]
    public string Lore { get; init; } = string.Empty;

    [JsonPropertyName("win_condition")]
    public string WinCondition { get; init; } = string.Empty;

    [JsonPropertyName("lose_condition")]
    public string LoseCondition { get; init; } = string.Empty;

    [JsonPropertyName("chapters")]
    public IReadOnlyList<ChapterDefinition> Chapters { get; init; } = Array.Empty<ChapterDefinition>();

    [JsonPropertyName("npcs")]
    public IReadOnlyList<NpcDefinition> Npcs { get; init; } = Array.Empty<NpcDefinition>();
}

public sealed class ChapterDefinition
{
    [JsonPropertyName("index")]
    public int Index { get; init; }

    [JsonPropertyName("title")]
    public string Title { get; init; } = string.Empty;

    [JsonPropertyName("summary")]
    public string Summary { get; init; } = string.Empty;

    [JsonPropertyName("scenes")]
    public IReadOnlyList<SceneDefinition> Scenes { get; init; } = Array.Empty<SceneDefinition>();
}

public sealed class SceneDefinition
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; init; } = string.Empty;

    [JsonPropertyName("active_npc_ids")]
    public IReadOnlyList<string> ActiveNpcIds { get; init; } = Array.Empty<string>();

    [JsonPropertyName("exits")]
    public IReadOnlyList<string> Exits { get; init; } = Array.Empty<string>();
}

public sealed class NpcDefinition
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("name")]
    public string Name { get; init; } = string.Empty;

    [JsonPropertyName("personality")]
    public string Personality { get; init; } = string.Empty;

    [JsonPropertyName("backstory")]
    public string Backstory { get; init; } = string.Empty;

    [JsonPropertyName("relationship_to_player")]
    public string RelationshipToPlayer { get; init; } = string.Empty;

    [JsonPropertyName("secrets")]
    public string Secrets { get; init; } = string.Empty;

    [JsonPropertyName("speech_style")]
    public string SpeechStyle { get; init; } = string.Empty;
}
