using UnityEngine;
using IronFlag.Core;
using IronFlag.Supply;
using IronFlag.Vehicles;

namespace IronFlag.Combat
{
    /// <summary>
    /// A gun: a muzzle, a rate of fire, the rounds that come out of it, and how many of
    /// those are left.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The gun fires where the muzzle points, and that one rule is the whole reason nothing
    /// here branches on what it is bolted to. The tank and the ASV mount their muzzle on a
    /// part that traverses, so their aim is the turret's and it takes time to get there; the
    /// jeep and the helicopter mount theirs on the hull, so their aim is wherever the nose
    /// is and they have to drive at what they want to hit. Two very different weapons, one
    /// line of code, and no way for the round to come out somewhere the barrel is not
    /// pointing.
    /// </para>
    /// <para>
    /// Named for the vehicle because for four milestones that is all there was, and it kept
    /// the name when <see cref="IronFlag.Destruction.AutoTurret"/> bolted one to a building:
    /// an emplacement is a muzzle on a part that traverses with an owner that is not a
    /// pilot, which is a mount this already describes. What it reads off its owner is two
    /// questions - whose side is this and is it still standing - and both are
    /// <see cref="IDamageable"/>, which a hull and a wall both answer. The
    /// <see cref="VehicleController"/> is the only vehicle-shaped thing left on here, it is
    /// optional, and all it does is supply a trigger finger.
    /// </para>
    /// <para>
    /// Only the horizontal part of that direction is used. A helicopter banking hard is
    /// tilting a cosmetic node (<see cref="Helicopter"/> keeps the tilt off the collider),
    /// and a gun that followed it would put rounds into the ground during every turn. What
    /// decides the shot's <em>vertical</em> angle is not the barrel at all: a lobbed round
    /// takes the arc its weapon was tuned for, and a flat one is aimed down onto the
    /// <see cref="CombatPlane"/> so that a helicopter ten metres up visibly fires at the
    /// ground it is hitting rather than level over the top of it.
    /// </para>
    /// <para>
    /// <see cref="TryFire"/> is also the one place in the game a shot is drawn from, which
    /// is why the muzzle flash is spawned here rather than in the two callers: a vehicle
    /// pulls its own trigger from <c>Update</c> and an emplacement pulls it from
    /// <see cref="IronFlag.Destruction.AutoTurret"/>, and both go through this method.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Vehicle Weapon")]
    public sealed class VehicleWeapon : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("Vehicle whose fire input this gun reads. Null on a mount nobody drives.")]
        private VehicleController vehicle;

        [SerializeField]
        [Tooltip("Point the rounds leave from. On a turreted vehicle it traverses with the gun.")]
        private Transform muzzle;

        [SerializeField]
        [Tooltip("Weapon numbers. Stamped from WeaponTuning.For(kind) when the prefab is built.")]
        private WeaponTuning tuning = new WeaponTuning();

        [SerializeField]
        [Tooltip("The round this gun fires. Generated by the combat prefab builder.")]
        private Projectile round;

        [SerializeField]
        [Tooltip("Flash drawn at the muzzle on every shot. Generated by the combat prefab builder.")]
        private MuzzleFlash flash;

        private IDamageable owner;
        private VehicleSupply supply;
        private bool looked;
        private float cooldown;

        /// <summary>The numbers this gun is firing with.</summary>
        public WeaponTuning Tuning => tuning;

        /// <summary>Where the rounds come out.</summary>
        public Transform Muzzle => muzzle;

        /// <summary>The flash this gun draws when it fires, or null for a gun that draws none.</summary>
        /// <remarks>
        /// Exposed so a test can tell a gun that was built without one from a gun that was
        /// built and then had its flash dropped by a change to the builder. Nothing in the
        /// game reads it; <see cref="TryFire"/> uses the field directly.
        /// </remarks>
        public MuzzleFlash Flash => flash;

        /// <summary>Seconds until this gun can fire again.</summary>
        public float Cooldown => Mathf.Max(0.0f, cooldown);

        /// <summary>Whether the gun would fire if the trigger were pulled right now.</summary>
        /// <remarks>
        /// A wrecked mount does not fire, and that is one question rather than two: a hull
        /// with no hit points and a turret that has been knocked to rubble are both an
        /// <see cref="IDamageable"/> answering <see cref="IDamageable.IsDestroyed"/>.
        /// </remarks>
        public bool IsLoaded
            => cooldown <= 0.0f && tuning.Exists && muzzle != null && round != null
                && !IsWrecked
                && (supply == null || !supply.IsOutOfAmmunition);

        /// <summary>Whether this gun has run out of ammunition.</summary>
        /// <remarks>
        /// False for a gun with no <see cref="VehicleSupply"/> behind it, which never runs
        /// out - see that component for why a test rig is allowed unlimited ammunition, and
        /// <see cref="WeaponTuning.Emplacement"/> for why an automated turret is too.
        /// </remarks>
        public bool IsEmpty => supply != null && supply.IsOutOfAmmunition;

        /// <summary>Whether whatever this gun is bolted to has been shot to pieces.</summary>
        private bool IsWrecked
        {
            get
            {
                Look();
                return owner != null && owner.IsDestroyed;
            }
        }

        /// <summary>
        /// Points this gun at its muzzle and stamps the numbers it fires with.
        /// </summary>
        /// <param name="driver">
        /// Vehicle whose fire input to read, or <c>null</c> for a mount nobody drives - see
        /// <see cref="IronFlag.Destruction.AutoTurret"/>, which pulls its own trigger.
        /// </param>
        /// <param name="muzzlePoint">Point the rounds leave from.</param>
        /// <param name="weapon">Weapon numbers to fire with.</param>
        /// <param name="projectile">Prefab of the round this gun fires.</param>
        /// <param name="muzzleFlash">
        /// Prefab of the flash drawn at the barrel, or <c>null</c> for a gun that draws
        /// none - which is what a rig assembled in a test is, exactly as it has no round.
        /// </param>
        /// <remarks>
        /// The flash comes through here rather than through a setter of its own so that a
        /// gun cannot exist half-wired: every mount in the game is built by one of two
        /// builders, and both of them name it. <see cref="SetMuzzle"/> is the exception it
        /// documents its own reason for.
        /// </remarks>
        public void Configure(
            VehicleController driver,
            Transform muzzlePoint,
            WeaponTuning weapon,
            Projectile projectile,
            MuzzleFlash muzzleFlash)
        {
            vehicle = driver;
            muzzle = muzzlePoint;
            tuning = weapon == null ? new WeaponTuning() : weapon;
            round = projectile;
            flash = muzzleFlash;
        }

        /// <summary>
        /// Moves this gun onto a different muzzle, leaving everything else alone.
        /// </summary>
        /// <param name="muzzlePoint">The new point rounds leave from, or null for none.</param>
        /// <remarks>
        /// For a mount whose barrel is part of a model that gets swapped:
        /// <see cref="IronFlag.Destruction.AutoTurret"/> has a different mesh per destruction
        /// state, so a shot-up turret fires out of the barrel it has left rather than out of
        /// where its intact one used to be. Deliberately not <see cref="Configure"/>, which
        /// would also reset the cooldown - a turret that could dodge its own rate of fire by
        /// being shot would fire faster the more damage it took.
        /// </remarks>
        public void SetMuzzle(Transform muzzlePoint) => muzzle = muzzlePoint;

        /// <summary>
        /// Fires one round if the gun is loaded.
        /// </summary>
        /// <returns><c>true</c> when a round left the barrel.</returns>
        /// <remarks>
        /// Public so a test can pull the trigger without a player holding it, and so a gun
        /// can be fired from somewhere other than the pilot's finger.
        /// </remarks>
        public bool TryFire()
        {
            if (!IsLoaded)
            {
                return false;
            }

            // A paused match sets Time.timeScale to zero but does not disable any
            // MonoBehaviour, so Update() keeps calling in here on every real frame - this is
            // the one place that stops a shot actually leaving the barrel while the pause
            // panel is up.
            if (Time.timeScale <= 0.0f)
            {
                return false;
            }

            ProjectileState launch = ProjectileMotion.Launch(
                muzzle.position, muzzle.forward, tuning.MuzzleSpeed, Elevation());

            if (Projectile.Fire(round, launch, tuning, TeamOfOwner(), transform) == null)
            {
                return false;
            }

            // After the round, not before it: a gun that flashed and then failed to produce
            // anything would be showing the player a shot that was never taken.
            MuzzleFlash.Spawn(flash, muzzle, tuning.Radius);

            if (supply != null)
            {
                // The round has left the barrel, so the box is one lighter. IsLoaded has
                // already established there was one in it to take.
                supply.TryTakeRound();
            }

            cooldown = tuning.ShotInterval;
            return true;
        }

        /// <summary>
        /// Returns the angle above the horizon to fire this shot at.
        /// </summary>
        /// <returns>The launch angle in degrees; negative points the round downwards.</returns>
        /// <remarks>
        /// A lobbed round has one angle, solved from its reach when the table was written. A
        /// flat one has a different angle every shot, because it depends on how high off the
        /// ground the muzzle currently is - which for the helicopter is wherever the pilot
        /// has flown it to.
        /// </remarks>
        private float Elevation()
            => tuning.Drop > 0.0f
                ? tuning.ElevationDegrees
                : CombatPlane.DepressionFrom(muzzle.position.y, tuning.Range);

        private Team TeamOfOwner()
        {
            Look();
            return owner == null ? Team.None : owner.Team;
        }

        /// <summary>
        /// Finds the mount this gun is bolted to, once.
        /// </summary>
        /// <remarks>
        /// Lazy rather than only in <c>Awake</c>, for the same reason
        /// <see cref="IronFlag.Destruction.Destructible"/> is: <c>Awake</c> does not run
        /// outside play mode, and the editor still asks a prefab on disk whether its gun is
        /// loaded.
        /// </remarks>
        private void Look()
        {
            if (looked)
            {
                return;
            }

            looked = true;
            owner = GetComponent<IDamageable>();
            supply = GetComponent<VehicleSupply>();
        }

        private void Awake() => Look();

        private void Update()
        {
            if (cooldown > 0.0f)
            {
                cooldown -= Time.deltaTime;
            }

            if (vehicle != null && vehicle.CurrentInput.Fire)
            {
                TryFire();
            }
        }
    }
}
