using UnityEngine;
using IronFlag.Core;
using IronFlag.Supply;
using IronFlag.Vehicles;

namespace IronFlag.Combat
{
    /// <summary>
    /// A vehicle's gun: a muzzle, a rate of fire, the rounds that come out of it, and how
    /// many of those are left.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The gun fires where the muzzle points, and that one rule is the whole reason nothing
    /// here branches on which vehicle it is bolted to. The tank and the ASV mount their
    /// muzzle on a part that traverses, so their aim is the turret's and it takes time to
    /// get there; the jeep and the helicopter mount theirs on the hull, so their aim is
    /// wherever the nose is and they have to drive at what they want to hit. Two very
    /// different weapons, one line of code, and no way for the round to come out somewhere
    /// the barrel is not pointing.
    /// </para>
    /// <para>
    /// Only the horizontal part of that direction is used. A helicopter banking hard is
    /// tilting a cosmetic node (<see cref="Helicopter"/> keeps the tilt off the collider),
    /// and a gun that followed it would put rounds into the ground during every turn. What
    /// decides the shot's <em>vertical</em> angle is not the barrel at all: a lobbed round
    /// takes the arc its weapon was tuned for, and a flat one is aimed down onto the
    /// <see cref="CombatPlane"/> so that a helicopter ten metres up visibly fires at the
    /// ground it is hitting rather than level over the top of it.
    /// </para>
    /// </remarks>
    [AddComponentMenu("IronFlag/Vehicle Weapon")]
    public sealed class VehicleWeapon : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("Vehicle whose fire input this gun reads.")]
        private VehicleController vehicle;

        [SerializeField]
        [Tooltip("Point the rounds leave from. On a turreted vehicle it traverses with the gun.")]
        private Transform muzzle;

        [SerializeField]
        [Tooltip("Weapon numbers. Stamped from WeaponTuning.For(kind) when the prefab is built.")]
        private WeaponTuning tuning = new WeaponTuning();

        [SerializeField]
        [Tooltip("The round this gun fires. Generated by the combat prefab builder.")]
        private Projectile round;

        private VehicleHealth health;
        private VehicleSupply supply;
        private float cooldown;

        /// <summary>The numbers this gun is firing with.</summary>
        public WeaponTuning Tuning => tuning;

        /// <summary>Where the rounds come out.</summary>
        public Transform Muzzle => muzzle;

        /// <summary>Seconds until this gun can fire again.</summary>
        public float Cooldown => Mathf.Max(0.0f, cooldown);

        /// <summary>Whether the gun would fire if the trigger were pulled right now.</summary>
        public bool IsLoaded
            => cooldown <= 0.0f && tuning.Exists && muzzle != null && round != null
                && (health == null || !health.IsDestroyed)
                && (supply == null || !supply.IsOutOfAmmunition);

        /// <summary>Whether this gun has run out of ammunition.</summary>
        /// <remarks>
        /// False for a gun with no <see cref="VehicleSupply"/> behind it, which never runs
        /// out - see that component for why a test rig is allowed unlimited ammunition.
        /// </remarks>
        public bool IsEmpty => supply != null && supply.IsOutOfAmmunition;

        /// <summary>
        /// Points this gun at its muzzle and stamps the numbers it fires with.
        /// </summary>
        /// <param name="owner">Vehicle whose fire input to read.</param>
        /// <param name="muzzlePoint">Point the rounds leave from.</param>
        /// <param name="weapon">Weapon numbers to fire with.</param>
        /// <param name="projectile">Prefab of the round this gun fires.</param>
        /// <remarks>Called by the prefab builder, and by anything that spawns a vehicle.</remarks>
        public void Configure(
            VehicleController owner, Transform muzzlePoint, WeaponTuning weapon, Projectile projectile)
        {
            vehicle = owner;
            muzzle = muzzlePoint;
            tuning = weapon == null ? new WeaponTuning() : weapon;
            round = projectile;
        }

        /// <summary>
        /// Fires one round if the gun is loaded.
        /// </summary>
        /// <returns><c>true</c> when a round left the barrel.</returns>
        /// <remarks>
        /// Public so a test can pull the trigger without a player holding it, and so a gun
        /// can be fired from somewhere other than the pilot's finger.
        /// </remarks>
        public bool TryFire()
        {
            if (!IsLoaded)
            {
                return false;
            }

            ProjectileState launch = ProjectileMotion.Launch(
                muzzle.position, muzzle.forward, tuning.MuzzleSpeed, Elevation());

            if (Projectile.Fire(round, launch, tuning, TeamOfOwner(), transform) == null)
            {
                return false;
            }

            if (supply != null)
            {
                // The round has left the barrel, so the box is one lighter. IsLoaded has
                // already established there was one in it to take.
                supply.TryTakeRound();
            }

            cooldown = tuning.ShotInterval;
            return true;
        }

        /// <summary>
        /// Returns the angle above the horizon to fire this shot at.
        /// </summary>
        /// <returns>The launch angle in degrees; negative points the round downwards.</returns>
        /// <remarks>
        /// A lobbed round has one angle, solved from its reach when the table was written. A
        /// flat one has a different angle every shot, because it depends on how high off the
        /// ground the muzzle currently is - which for the helicopter is wherever the pilot
        /// has flown it to.
        /// </remarks>
        private float Elevation()
            => tuning.Drop > 0.0f
                ? tuning.ElevationDegrees
                : CombatPlane.DepressionFrom(muzzle.position.y, tuning.Range);

        private Team TeamOfOwner() => health == null ? Team.None : health.Team;

        private void Awake()
        {
            health = GetComponent<VehicleHealth>();
            supply = GetComponent<VehicleSupply>();
        }

        private void Update()
        {
            if (cooldown > 0.0f)
            {
                cooldown -= Time.deltaTime;
            }

            if (vehicle != null && vehicle.CurrentInput.Fire)
            {
                TryFire();
            }
        }
    }
}
