<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>AdventureEngine.Web</AssemblyName>
    <RootNamespace>AdventureEngine.Web</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdventureEngine.Application\AdventureEngine.Application.csproj" />
    <ProjectReference Include="..\AdventureEngine.Infrastructure\AdventureEngine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
  </ItemGroup>

</Project>
