<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <AdditionalFiles Include="*.yaml" />
    <AdditionalFiles Include="src/props/**" />
  </ItemGroup>
  
  <ItemGroup>
    <AdditionalFiles Remove="tests\AiUsageMonitor.Tests\AiUsageMonitor.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".env.example" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="DotNetProjectFile.Analyzers.Sdk" PrivateAssets="all" />
  </ItemGroup>

</Project>