name: Request Unity Activation File
on: workflow_dispatch
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: game-ci/unity-request-activation-file@v2
        id: request
        with:
          unity-version: 6000.5.9f1
      - uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: ${{ steps.request.outputs.filePath }}